package com.ray.core.dao;

import com.ray.core.model.MenuAdmin;

public interface MenuAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_admin
     *
     * @mbggenerated
     */
    int insert(MenuAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_admin
     *
     * @mbggenerated
     */
    int insertSelective(MenuAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_admin
     *
     * @mbggenerated
     */
    MenuAdmin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MenuAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MenuAdmin record);
}