package com.ray.core.model;

import java.util.Date;

public class MenuAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.menu_name
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.menu_code
     *
     * @mbggenerated
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.menu_url
     *
     * @mbggenerated
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.grade
     *
     * @mbggenerated
     */
    private Byte grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.sequence
     *
     * @mbggenerated
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.super_id
     *
     * @mbggenerated
     */
    private Long superId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.is_show
     *
     * @mbggenerated
     */
    private Byte isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_admin.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.id
     *
     * @return the value of menu_admin.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.id
     *
     * @param id the value for menu_admin.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.menu_name
     *
     * @return the value of menu_admin.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.menu_name
     *
     * @param menuName the value for menu_admin.menu_name
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.menu_code
     *
     * @return the value of menu_admin.menu_code
     *
     * @mbggenerated
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.menu_code
     *
     * @param menuCode the value for menu_admin.menu_code
     *
     * @mbggenerated
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.menu_url
     *
     * @return the value of menu_admin.menu_url
     *
     * @mbggenerated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.menu_url
     *
     * @param menuUrl the value for menu_admin.menu_url
     *
     * @mbggenerated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.grade
     *
     * @return the value of menu_admin.grade
     *
     * @mbggenerated
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.grade
     *
     * @param grade the value for menu_admin.grade
     *
     * @mbggenerated
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.sequence
     *
     * @return the value of menu_admin.sequence
     *
     * @mbggenerated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.sequence
     *
     * @param sequence the value for menu_admin.sequence
     *
     * @mbggenerated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.super_id
     *
     * @return the value of menu_admin.super_id
     *
     * @mbggenerated
     */
    public Long getSuperId() {
        return superId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.super_id
     *
     * @param superId the value for menu_admin.super_id
     *
     * @mbggenerated
     */
    public void setSuperId(Long superId) {
        this.superId = superId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.is_show
     *
     * @return the value of menu_admin.is_show
     *
     * @mbggenerated
     */
    public Byte getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.is_show
     *
     * @param isShow the value for menu_admin.is_show
     *
     * @mbggenerated
     */
    public void setIsShow(Byte isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.gmt_create
     *
     * @return the value of menu_admin.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.gmt_create
     *
     * @param gmtCreate the value for menu_admin.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_admin.gmt_modified
     *
     * @return the value of menu_admin.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_admin.gmt_modified
     *
     * @param gmtModified the value for menu_admin.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}