package com.ray.core.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.mlevel
     *
     * @mbggenerated
     */
    private Integer mlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.resourceURL
     *
     * @mbggenerated
     */
    private String resourceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.smenCaption
     *
     * @mbggenerated
     */
    private String smencaption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.smenHint
     *
     * @mbggenerated
     */
    private String smenhint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.smenIcon
     *
     * @mbggenerated
     */
    private String smenicon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.smenIndex
     *
     * @mbggenerated
     */
    private Integer smenindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.systemMenu
     *
     * @mbggenerated
     */
    private Long systemmenu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.mlevel
     *
     * @return the value of menu.mlevel
     *
     * @mbggenerated
     */
    public Integer getMlevel() {
        return mlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.mlevel
     *
     * @param mlevel the value for menu.mlevel
     *
     * @mbggenerated
     */
    public void setMlevel(Integer mlevel) {
        this.mlevel = mlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.resourceURL
     *
     * @return the value of menu.resourceURL
     *
     * @mbggenerated
     */
    public String getResourceurl() {
        return resourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.resourceURL
     *
     * @param resourceurl the value for menu.resourceURL
     *
     * @mbggenerated
     */
    public void setResourceurl(String resourceurl) {
        this.resourceurl = resourceurl == null ? null : resourceurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.smenCaption
     *
     * @return the value of menu.smenCaption
     *
     * @mbggenerated
     */
    public String getSmencaption() {
        return smencaption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.smenCaption
     *
     * @param smencaption the value for menu.smenCaption
     *
     * @mbggenerated
     */
    public void setSmencaption(String smencaption) {
        this.smencaption = smencaption == null ? null : smencaption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.smenHint
     *
     * @return the value of menu.smenHint
     *
     * @mbggenerated
     */
    public String getSmenhint() {
        return smenhint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.smenHint
     *
     * @param smenhint the value for menu.smenHint
     *
     * @mbggenerated
     */
    public void setSmenhint(String smenhint) {
        this.smenhint = smenhint == null ? null : smenhint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.smenIcon
     *
     * @return the value of menu.smenIcon
     *
     * @mbggenerated
     */
    public String getSmenicon() {
        return smenicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.smenIcon
     *
     * @param smenicon the value for menu.smenIcon
     *
     * @mbggenerated
     */
    public void setSmenicon(String smenicon) {
        this.smenicon = smenicon == null ? null : smenicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.smenIndex
     *
     * @return the value of menu.smenIndex
     *
     * @mbggenerated
     */
    public Integer getSmenindex() {
        return smenindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.smenIndex
     *
     * @param smenindex the value for menu.smenIndex
     *
     * @mbggenerated
     */
    public void setSmenindex(Integer smenindex) {
        this.smenindex = smenindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.systemMenu
     *
     * @return the value of menu.systemMenu
     *
     * @mbggenerated
     */
    public Long getSystemmenu() {
        return systemmenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.systemMenu
     *
     * @param systemmenu the value for menu.systemMenu
     *
     * @mbggenerated
     */
    public void setSystemmenu(Long systemmenu) {
        this.systemmenu = systemmenu;
    }
}